# Generated by Django 4.0.6 on 2023-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_categorias_cursoid_cursos_categoriaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CursoId', models.IntegerField(default=0)),
                ('EstudianteID', models.IntegerField(default=0)),
                ('Fecha', models.CharField(max_length=20)),
            ],
        ),
    ]
