# Generated by Django 4.0.6 on 2023-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Descripcion',
            field=models.TextField(),
        ),
    ]
