# Generated by Django 4.0.6 on 2023-07-29 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_alter_categorias_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('number_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
